config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dishes#index'
  resources :dishes
  resources :ingredients
  get '/search/ingredients', to: 'ingredients#search'
  get 'my_dishes', to: 'dishes#my_dishes'
  get 'my_ingredients', to: 'ingredients#my_ingredients'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users
  authenticated do
    root to: 'dishes#index', as: :authenticated_root
  end
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  scope :active, -> { where(status: "active") }
  has_many :dish_ingredients
  has_many :dishes, through: :dish_ingredients
  enum status: { active: 0, disabled: 1 }
  belongs_to :user
  validates :name, presence: true
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy my_ingredients]
  before_action :set_ingredient, only: %i[show edit update destroy]

  def index
    @ingredients = if params[:q]
                     Ingredient.active.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
                   else
                     Ingredient.active
                   end
    respond_to do |format|
      format.json { render json: @ingredients, layout: false }
      format.html {}
    end
  end

  def my_ingredients
    @ingredients = if params[:q]
                     current_user.ingredients.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
                   else
                     current_user.ingredients
                   end
  end

  def search
    @ingredients = if params[:q]
                     Ingredient.where("lower(name) LIKE ?", "%#{params[:q].downcase}%").all
                   else
                     []
                   end
    render layout: false
  end

  def show
    redirect_to ingredients_path unless @ingredient&.active?
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
    return if current_user.admin? || current_user.moderator? || current_user.id == @ingredient.user_id

    redirect_to ingredients_path, alert: "Permission denied",
                                  status: :unauthorized
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.user_id = current_user.id
    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to ingredient_url(@ingredient), notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # @ingredient.destroy
    @ingredient.status = 1
    @ingredient.save
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully disabled.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_ingredient
    @ingredient = Ingredient.find_by(id: params[:id])
    redirect_to ingredients_path unless @ingredient
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :description)
  end
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, class: "contents") do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", :required => true %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"%>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id ingredient %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= ingredient.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= ingredient.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ingredient", ingredient, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if  user_signed_in? && (current_user.role == 'admin' || current_user.id == ingredient.user_id) %>
      <%= link_to 'Edit this ingredient', edit_ingredient_path(ingredient), class: "rounded-lg py-3 ml-2 px-5 bg-blue-100 text-blue-500 inline-block font-medium" %>
    <% end %>
  <% end %>
  <hr class="mt-6">
</div>

app/views/ingredients/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to "Show this ingredient", @ingredient, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ingredients", ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ingredients/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ingredients</h1>
    <% if  user_signed_in? %>
      <%= link_to 'New ingredient', new_ingredient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>

  </div>
  <div class="my-5">
    <form action="/ingredients" class="inline">
      <input type="text" id="q" name="q" placeholder="Busca un ingrediente" class="focus:ring-indigo-500 py-3 px-5 focus:border-indigo-500 block w-1/2 pl-7 pr-12 sm:text-sm border-gray-300 rounded-md inline-block">
      <input type="submit" value="Buscar" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer ">
    </form>
  </div>
  <div id="ingredients" class="min-w-full">
    <%= render @ingredients %>
  </div>
</div>

app/views/ingredients/my_ingredients.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">My Ingredients</h1>
    <% if  user_signed_in? %>
      <%= link_to 'New ingredient', new_ingredient_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>

  </div>
  <div class="my-5">
    <form action="/my_ingredients" class="inline">
      <input type="text" id="q" name="q" placeholder="Busca un ingrediente" class="focus:ring-indigo-500 py-3 px-5 focus:border-indigo-500 block w-1/2 pl-7 pr-12 sm:text-sm border-gray-300 rounded-md inline-block">
      <input type="submit" value="Buscar" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer ">
    </form>
  </div>
  <div id="ingredients" class="min-w-full">
    <%= render @ingredients %>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New ingredient</h1>

  <%= render "form", ingredient: @ingredient %>

  <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ingredients/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @ingredient %>
    <% if user_signed_in? && (current_user.role == 'admin' || current_user.id == @ingredient.user_id) %>
    <%= link_to 'Edit this ingredient', edit_ingredient_path(@ingredient), class: "mt-2 rounded-lg py-3 px-5 bg-blue-100 text-blue-500 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= link_to "Delete this ingredient", ingredient_path(@ingredient), data: {
        turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "mt-2 rounded-lg py-3 px-5 bg-red-50 text-red-500 font-medium" %>
    </div>
    <% end %>
    <%= link_to 'Show dishes to make', dishes_path( :ingredient => @ingredient.id) , class: "mt-2 rounded-lg py-3 px-5 bg-blue-100 text-blue-500 inline-block font-medium" %>
    <%= link_to 'Back to ingredients', ingredients_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>