config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dishes#index'
  resources :dishes
  resources :ingredients
  get '/search/ingredients', to: 'ingredients#search'
  get 'my_dishes', to: 'dishes#my_dishes'
  get 'my_ingredients', to: 'ingredients#my_ingredients'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users
  authenticated do
    root to: 'dishes#index', as: :authenticated_root
  end
end

app/models/dish.rb
# frozen_string_literal: true

class Dish < ApplicationRecord
  belongs_to :user
  has_many :dish_ingredients, dependent: :destroy
  has_many :ingredients, through: :dish_ingredients
  has_one_attached :image

  validates :name, presence: true

  def save_ingredients(ingredients)
    result = true
    DishIngredient.transaction do
      ingredients.each do |ingredient|
        logger.info "@----------------------------------------------------- Dish id: #{id} "
        new_dish_ingredient = DishIngredient.new(
          dish_id: id,
          ingredient_id: ingredient
        )
        unless new_dish_ingredient.save
          result = false
          raise ActiveRecord::Rollback, "Dish Ingredient not saved"
        end
      end
    end
    result
  end
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

class DishesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy my_dishes]
  before_action :set_dish, only: %i[show edit update destroy]

  def index
    @dishes = if params[:q]
                Dish.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
              else
                Dish.all
              end
    return unless params[:ingredient]

    @dishes = @dishes.joins(:dish_ingredients).where(dish_ingredients: { ingredient_id: params[:ingredient].to_s })
  end

  def my_dishes
    @dishes = if params[:q]
                current_user.dishes.where("lower(name) LIKE ?", "%#{params[:q].downcase}%")
              else
                current_user.dishes
              end
  end

  def show; end

  def new
    @dish = Dish.new
    @ingredients = []
  end

  def edit
    return if current_user.admin? || current_user.moderator? || current_user.id == @dish.user_id

    redirect_to dishes_path, alert: "Permission denied",
                             status:	:unauthorized
  end

  def create
    @dish = Dish.new(dish_params)
    @dish.user_id = current_user.id
    if @dish.save
      @dish.save_ingredients(params[:dish][:ingredients].map(&:to_i)) if params[:dish][:ingredients]
      redirect_to dish_url(@dish), notice: "Dish was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    logger.info "@----------------------------------------------------- Update params "
    if @dish.update(dish_params)
      @dish.dish_ingredients.destroy_all if params[:dish][:ingredients]
      @dish.save_ingredients(params[:dish][:ingredients].map(&:to_i)) if params[:dish][:ingredients]
      redirect_to dish_url(@dish), notice: "Dish was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: "Dish was successfully destroyed.", status: :see_other
  end

  private

  def set_dish
    @dish = Dish.find_by(id: params[:id])
    if @dish
      @ingredients = @dish.ingredients
    else
      redirect_to dishes_path
    end
  end

  def dish_params
    params.require(:dish).permit(:name, :description, :image)
  end
end

app/helpers/dishes_helper.rb
# frozen_string_literal: true

module DishesHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">

  <p class="my-5">
    <ul>
      <% if dish.image%>
        <li>
          <% if dish.image.representable? %>
          <div class="">
            <%= image_tag dish.image, class:"" %>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </p>
  <p class="my-5">
    <strong class="block mb-1">Name:</strong>
    <%= dish.name %>
  </p>

  <p class="my-5">
    <strong class="block mb-1">Description:</strong>
    <%= dish.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this dish", dish, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if  user_signed_in? && (current_user.role == 'admin' || current_user.id == dish.user_id ) %>
      <%= link_to 'Edit this dish', edit_dish_path(dish), class: "rounded-lg py-3 ml-2 px-5 bg-blue-100 text-blue-500 inline-block font-medium" %>
    <% end %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/dishes/_form.html.erb
<div data-controller="dish-form">
  <%= form_with(model: dish, class: "contents") do |form| %>
    <% if dish.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

        <ul>
          <% dish.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
    <% if dish.image%>
          <% if dish.image.representable? %>
            <%= image_tag dish.image %>
          <% end %>
      <% end %>
    </div>
    <div class="my-5">
      <%= form.file_field :image %>

    </div>
    <div class="my-5">
      <%= form.label :name %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" , :required => true %>
    </div>

    <div class="my-5">
      <%= form.label :description %>
      <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <label>Ingredientes</label>
      <ul class="divide-y  shadow-lg" data-dish-form-target="ingredientsList" >
        <%=render partial: 'dishes/ingredient', collection: ingredients%>
      </ul>
      <label>Add two or more ingredients to create a dish</label>
    </div>

    <div class="my-5 container" id="autocompleteArea">
      <div class="relative">
      <input type="hidden" data-dish-form-target="ingredientId">
      <input
        type="text"
        data-dish-form-target="ingredientAutocomplete"
        class="z-0 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
        >
      <div class="absolute top-2 right-2">
        <button
          disabled
          type="button"
          data-dish-form-target="btnAddIngredient"
          data-action="click->dish-form#addIngredient"
          title="Please select an ingredient before adding it to the dish"
          class="h-7 w-8 text-white rounded-lg bg-blue-200 hover:bg-blue-300 shadow"
          >+</button>
      </div>
      </div>
      <ul data-dish-form-target="suggestions" class="divide-y rounded-md shadow-lg">
      </ul>
    </div>


    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer", :disabled => true, :"data-dish-form-target" => 'submitBtn', :title => 'Please add two or more ingredients to enable this button' %>
      <%= link_to "Back to dishes", dishes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>

  <% end %>
</div>

app/views/dishes/_ingredient.html.erb
<div class="relative" id="<%= dom_id ingredient %>">
    <input
        type="hidden"
        value="<%= ingredient.id %>"
        name="dish[ingredients][]"/>
    <% if action_name != "show"%>
        <li class="text-gray-900 cursor-default  relative py-1 pl-3 pr-9">
            <%= ingredient.name %>
        </li>
        <div class="absolute top-1 right-2">
            <button
            type="button"
            data-action="click->dish-form#removeIngredient"
            class="h-6 w-8 text-white rounded-lg bg-red-500 hover:bg-red-600 shadow"
            title="Remove"
            >-</button>
        </div>
    <% else %>
        <% if ingredient.active? %>
            <%= link_to(ingredient) do%>
                <li class="text-gray-900 cursor-default  relative py-1 pl-3 pr-9 hover:bg-blue-200 cursor-pointer">
                        <%= ingredient.name %>
                </li>
            <% end %>
        <% else %>
            <li class="text-gray-900 cursor-default  relative py-1 pl-3 pr-9">
                    <%= ingredient.name %>
            </li>
        <% end %>
    <% end %>

</div>

app/views/dishes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing dish</h1>

  <%= render "form", dish: @dish, ingredients: @ingredients %>

  <%= link_to "Show this dish", @dish, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

</div>

app/views/dishes/index.html.erb
<div class="w-full" data-controller="hello" >
<% if  alert.present?%>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
<% end %>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Dishes</h1>
    <% if  user_signed_in? %>
      <%= link_to 'New dish', new_dish_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>

  </div>
 <div class="my-5">
    <form action="/dishes" class="inline">
      <input type="text" id="q" name="q" placeholder="Busca un platillo" class="focus:ring-indigo-500 py-3 px-5 focus:border-indigo-500 block w-1/2 pl-7 pr-12 sm:text-sm border-gray-300 rounded-md inline-block">
      <input type="submit" value="Buscar" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer ">
    </form>
  </div>
  <div id="dishes" class="min-w-full">
    <%= render @dishes %>
  </div>
</div>

app/views/dishes/my_dishes.html.erb
<div class="w-full" data-controller="hello" >
<% if  alert.present?%>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
<% end %>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">My Dishes</h1>
    <% if  user_signed_in? %>
      <%= link_to 'New dish', new_dish_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>

  </div>
 <div class="my-5">
    <form action="/my_dishes" class="inline">
      <input type="text" id="q" name="q" placeholder="Busca un platillo" class="focus:ring-indigo-500 py-3 px-5 focus:border-indigo-500 block w-1/2 pl-7 pr-12 sm:text-sm border-gray-300 rounded-md inline-block">
      <input type="submit" value="Buscar" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer ">
    </form>
  </div>
  <div id="dishes" class="min-w-full">
    <%= render @dishes %>
  </div>
</div>

app/views/dishes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New dish</h1>

  <%= render "form", dish: @dish, ingredients: @ingredients %>

</div>

app/views/dishes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @dish %>

    <strong class="block mb-1">Ingredients</strong>
    <ul class="divide-y  shadow-lg" data-dish-form-target="ingredientsList" >
      <%=render partial: 'dishes/ingredient', collection: @ingredients%>
    </ul>
    <% if  user_signed_in? && (current_user.role == 'admin' || current_user.id == @dish.user_id)%>

    <%= link_to 'Edit this dish', edit_dish_path(@dish), class: "mt-2 rounded-lg py-3 px-5 bg-blue-100 text-blue-500 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= link_to "Delete this dish", dish_path(@dish), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    }, class: "mt-2 rounded-lg py-3 px-5 bg-red-50 text-red-500 font-medium" %>
    </div>
    <% end %>
    <%= link_to 'Back to dishes', dishes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>