config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dishes#index'
  resources :dishes
  resources :ingredients
  get '/search/ingredients', to: 'ingredients#search'
  get 'my_dishes', to: 'dishes#my_dishes'
  get 'my_ingredients', to: 'ingredients#my_ingredients'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :users
  authenticated do
    root to: 'dishes#index', as: :authenticated_root
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-blue-600 p-6">
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
    <% if user_signed_in? %>
      <div class="block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base mr-4">
                User: <%= current_user.name.upcase     %>
            </div>
            <%end%>
      <%= link_to(user_signed_in? ? authenticated_root_path : root_path, class: 'block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4')  do %>
        FoodShareBook
        <% end %>
      <%= link_to "Dishes", dishes_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4"  %>
      <%= link_to "Ingredients", ingredients_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4"  %>
      <% if user_signed_in? %>

            <%= link_to "My dishes", my_dishes_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4" %>
            <%= link_to "My ingredients", my_ingredients_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4" %>
            <% if  current_user.role == 'admin'%>
              <%= link_to "Users", users_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4"   %>
            <% end %>
            <div class="inline-block">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white' %>
            </div>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 text-base hover:text-white mr-4" %>
          <% end %>
    </div>
  </div>
</nav>